# Generated by Django 5.2.14 on 2026-06-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
