# Generated by Django 5.2.14 on 2026-06-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('duration_days', models.IntegerField(default=1)),
            ],
        ),
    ]
